### ISSUE TITLE
Script extension conflicts with the Jupyter one

### ISSUE THREAD

**Issue by Keniamin** [nurmohammed840/achievement#13]
Good day! I'm using Script extension to add some useful commands into my VS Code. Recently I've installed Jupyter extension to work with my Python code interactively. But when I'm trying to run some code, and Jupyter trying to start a Python kernel for it, the following exception occurs:
```
Error 20:08:15: DataScience Error [o [Error]: 
	at new o (.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:16:33604)
	at Function.from (.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:16:33694)
	at .vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:24:87382
	at processTicksAndRejections (internal/process/task_queues.js:93:5)

TypeError: Cannot read property 'makeSettings' of undefined
	at p (.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:51:188821)
	at new t.RawSession (.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:104:351866)
	at S.startRawSession (.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:51:738866)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)] {
  category: 'unknown',
  originalException: [TypeError: Cannot read property 'makeSettings' of undefined
  	at p (.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:51:188821)
  	at new t.RawSession (.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:104:351866)
  	at S.startRawSession (.vscode\extensions\ms-toolsai.jupyter-2021.11.1001550889\out\client\extension.js:51:738866)
  	at processTicksAndRejections (internal/process/task_queues.js:93:5)]
}
```

The corresponding issue in the Jupyter extension Github repo leads me to the solution: find and disable the conflicting extension. I've tried some and found Script extension as the problematic one. When I disable it, all my other extensions works well with the Jupyter, so it looks like problem in the Script extension itself. Can you please take a look on this?

Some (maybe useful) info about the problem could be found in the Jupyter issue discussion:
https://github.com/microsoft/vscode-jupyter/issues/834

**Comment by nurmohammed840** [comment]
Thanks for your feedback!  Could you please share a minimal, reproducible example...

**Comment by Keniamin** [comment]
Not sure what "example" means here... Steps to reproduce:
1. Install Script extension and Jupyter one.
2. Configure Jupyter extension (not sure, may require also Python extension and Python interpreter itself, can be downloaded from the [official site](https://www.python.org/downloads/)).
3. Run "Jupyter: Create new Jupyter notebook" command.
4. Print any code to cell, for example "a = 0".
5. Execute a cell (button in upper left corner, see the screenshot).

![2022-01-22_00-36-11](https://user-images.githubusercontent.com/10873738/150603441-fa509834-364b-4b6e-b4da-cbbc239be3a0.png)

**Comment by nurmohammed840** [comment]
Thanks Again! 

I am not sure that if it cause such  issues... Maybe a bug in Jupiter kernel itself...
I didn't tried you example because, It lack some details... Also error message is confusing...

Also I found no suspicious code unit, that would could cause such issue. But I will again look into this...
If you still facing this problem or had any questions... feel free to ask!
